# Generated by Django 5.1 on 2024-08-21 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('AnalyticsID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalMatches', models.IntegerField()),
                ('WonMatches', models.IntegerField()),
                ('Score', models.IntegerField()),
                ('Rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('TournamentsID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('LastLogin', models.DateTimeField(auto_now=True)),
                ('Gender', models.IntegerField()),
                ('Analytics', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.analytics')),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshToken', models.CharField(max_length=255)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('MessageID', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('Content', models.TextField()),
                ('Status', models.CharField(max_length=255)),
                ('SenderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('MatchID', models.AutoField(primary_key=True, serialize=False)),
                ('MatchDate', models.DateTimeField()),
                ('TournamentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tournaments')),
                ('Player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_matches', to='api.users')),
                ('Player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_matches', to='api.users')),
                ('Player3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3_matches', to='api.users')),
                ('Player4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4_matches', to='api.users')),
                ('WinnerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipants',
            fields=[
                ('ParticipantsID', models.AutoField(primary_key=True, serialize=False)),
                ('Score', models.IntegerField()),
                ('Rank', models.IntegerField()),
                ('TournamentsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournaments')),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'indexes': [models.Index(fields=['TournamentsID'], name='api_tournam_Tournam_b22388_idx'), models.Index(fields=['PlayerID'], name='api_tournam_PlayerI_52c112_idx')],
                'unique_together': {('TournamentsID', 'PlayerID')},
            },
        ),
    ]
