# Generated by Django 5.1 on 2024-08-29 07:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.AutoField(db_column='analytics_id', primary_key=True, serialize=False)),
                ('total_matches', models.IntegerField(db_column='total_matches', default=0)),
                ('won_matches', models.IntegerField(db_column='won_matches', default=0)),
                ('score', models.IntegerField(db_column='score', default=0)),
                ('rank', models.IntegerField(db_column='rank', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('tournaments_id', models.AutoField(db_column='tournaments_id', primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(db_column='start_date')),
                ('end_date', models.DateTimeField(db_column='end_date')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], db_column='status', default='upcoming', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('surname', models.CharField(db_column='surname', max_length=255)),
                ('username', models.CharField(db_column='username', max_length=255, unique=True)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('last_login', models.DateTimeField(auto_now=True, db_column='last_login')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_column='gender', max_length=10)),
                ('analytics', models.OneToOneField(blank=True, db_column='analytics', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.analytics')),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(db_column='refresh_token', max_length=255)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.AutoField(db_column='message_id', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_column='timestamp', default=django.utils.timezone.now)),
                ('content', models.TextField(db_column='content')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], db_column='status', default='sent', max_length=255)),
                ('sender_id', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.AutoField(db_column='match_id', primary_key=True, serialize=False)),
                ('match_date', models.DateTimeField(db_column='match_date')),
                ('tournament_id', models.ForeignKey(blank=True, db_column='tournament_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tournaments')),
                ('player1', models.ForeignKey(db_column='player1', on_delete=django.db.models.deletion.CASCADE, related_name='player1_matches', to='api.users')),
                ('player2', models.ForeignKey(db_column='player2', on_delete=django.db.models.deletion.CASCADE, related_name='player2_matches', to='api.users')),
                ('player3', models.ForeignKey(blank=True, db_column='player3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3_matches', to='api.users')),
                ('player4', models.ForeignKey(blank=True, db_column='player4', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4_matches', to='api.users')),
                ('winner_id', models.ForeignKey(blank=True, db_column='winner_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipants',
            fields=[
                ('participants_id', models.AutoField(db_column='participants_id', primary_key=True, serialize=False)),
                ('score', models.IntegerField(db_column='score', default=0)),
                ('rank', models.IntegerField(db_column='rank', default=0)),
                ('tournaments_id', models.ForeignKey(db_column='tournaments_id', on_delete=django.db.models.deletion.CASCADE, to='api.tournaments')),
                ('player_id', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'indexes': [models.Index(fields=['tournaments_id'], name='api_tournam_tournam_acbf00_idx'), models.Index(fields=['player_id'], name='api_tournam_player__7183d6_idx')],
                'unique_together': {('tournaments_id', 'player_id')},
            },
        ),
    ]
